---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Install the latest version of lvm
      yum:
        name: lvm2
        state: latest

    - name: Install the latest version of Apache
      yum:
        name: httpd
        state: latest
